# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20f948e2f864739f1e0c55cf0cf4b184021181762d602220e48f30da3b7f8aac8799fc0fd6212d50c4994ad13939f671188492b7ddaacf00a6eefd7748576fdf

test:
  secret_key_base: 7287f84949a3c78ab72da64774d4513d817ce01df20b108185dafd67f714ef4f212fab2a6ba3c3ceb67c9c009bdbd57491884988e0cfd32b96005d8d68035d81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
